services:
  - type: web
    name: padho-abhi-api
    env: python
    branch: main
    plan: free
    autoDeploy: true
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn smartstudy.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        value: ""
        secure: true
      - key: GEMINI_API_KEY
        value: ""
        secure: true
      - key: PYTHONUNBUFFERED
        value: "1"